name: CI

on:
  push:
    branches: [ main, refactoring ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true

  release:
    name: Release
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for release
        run: npm run build:advanced

      - name: Create release artifacts
        run: |
          mkdir -p release
          cp builds/standalone/bear-mcp-server.js release/
          cp README.md LICENSE release/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bear-mcp-server
          path: release/ 